name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/hadolint.yml"
      - "Dockerfile"
      - ".hadolint.yaml"
  pull_request:
    paths:
      - ".github/workflows/hadolint.yml"
      - "Dockerfile"
      - ".hadolint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read
    uses: peaceiris/workflows/.github/workflows/hadolint.yml@99f66a30a38f806fd0df9014275c7cef0b6d9ca5 # v0.21.6
