name: hadolint

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/hadolint.yml"
      - "Dockerfile"
      - ".hadolint.yaml"
  pull_request:
    paths:
      - ".github/workflows/hadolint.yml"
      - "Dockerfile"
      - ".hadolint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read
    uses: peaceiris/workflows/.github/workflows/hadolint.yml@abcd9011b4dcbb803ab9454459030da9b9f0b2ab # v0.21.3
